baseurl = "http://jmgomezr.com"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]
googleAnalytics = ""
languageCode = "en-us"
theme = "hugo-split-theme"
title = "jmgomezr personal site"
[params]
copyright = "&copy;2017 Your Name"
description = "Split is a centrally-divided layout for a professional online presence with a big image or video left with alongside content."
favicon = "favicon.ico"
name = "Jose M. Gómez"
shareimage = "images/social.jpg"
twitterhandle = "onepagelove"
[params.content]
bio = "Hello there.<br> I am a computer engineer. This is my personal page. You can contact me on any of the social media apps displayed below."
name = "Jose M. Gómez"
tagline = "Software Developer. Techie."
[params.visual.image]
enable = true
file = "images/background.jpg"
position = "center center"
[params.visual.video]
enable = false
file = "videos/background.mp4"
mute = true
[[params.links]]
[params.links.list1]
heading = "Connect"
[[params.links.list1.link]]
text = "Blog"
url = "#"
[[params.links.list1.link]]
text = "Email"
url = "#"
[[params.links.list1.link]]
text = "Newsletter"
url = "#"
[[params.links]]
[params.links.list2]
heading = "Social"
[[params.links.list2.link]]
text = "Twitter"
url = "#"
[[params.links.list2.link]]
text = "Instagram"
url = "#"
[[params.links.list2.link]]
text = "Dribbble"
url = "#"
[[params.links]]
[params.links.list3]
heading = "Network"
[[params.links.list3.link]]
text = "Link One"
url = "#"
[[params.links.list3.link]]
text = "Link Two"
url = "#"
[[params.links.list3.link]]
text = "Link Three"
url = "#"
